#!/bin/python

import sys

def maxScoreOfVincent(n, s, t):
    if(s==t):
        return 0
    else:
        c=0
        for i in xrange(len(s)):
            if (s[i]!=t[i] and s[i]!='.'):
                c=c+1
        return c
    

#  Return the maximum score of Vincent.
n = int(raw_input().strip())
s = raw_input().strip()
t = raw_input().strip()
result = maxScoreOfVincent(n, s, t)
print(result)
